import { Component, OnInit } from '@angular/core';
import { UseCase } from '../usecase.model';

@Component({
  selector: 'client-side-web-frameworks-individual-about-usecases',
  templateUrl: './usecases.component.html',
  styleUrls: ['./usecases.component.css'],
})
export class UsecasesComponent implements OnInit {
  readonly PLAIN_USER = 'Reguliere gebruiker';
  readonly ADMIN_USER = 'Administrator';

  useCases: UseCase[] = [
    {
      id: 'UC-100',
      name: 'Inloggen',
      description: 'Hiermee logt een bestaande gebruiker in.',
      scenario: [
        'Gebruiker vult email en password in en klikt op Login knop.',
        'De applicatie valideert de ingevoerde gegevens.',
        'Indien gegevens correct zijn dan redirect de applicatie naar het startscherm.',
      ],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'Geen',
      postcondition: 'De actor is ingelogd.',
    },
    {
      id: 'UC-101',
      name: 'Uitloggen',
      description: 'Hiermee logt een ingelogde gebruiker uit.',
      scenario: [
        'Gebruiker klikt op zijn profiel.',
        'Er opent een dropdown menu met verschillende opties.',
        'Gebruiker klikt op uitloggen.',
      ],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'De actor is ingelogd',
      postcondition: 'De actor is uitgelogd.',
    },
    {
      id: 'UC-102',
      name: 'Registreren',
      description: 'Hiermee maakt een nieuwe gebruiker een account aan.',
      scenario: [
        'Gebruiker klikt op registreren.',
        'Er verschijnt een pagina waarop een gebruiker zijn gegevens moet invullen.',
        'Gebruiker vult de velden in.',
        'Gebruiker klikt op registreer.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: `${this.PLAIN_USER}`,
      precondition: 'Geen',
      postcondition: 'De actor is ingelogd.',
    },
    {
      id: 'UC-200',
      name: 'Aanmaken film',
      description: 'Hiermee maakt een administrator een nieuwe film aan.',
      scenario: [
        'Actor klikt op de films knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle films.',
        'Actor klikt op het + icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden.',
        'Actor vult de velden in.',
        'Actor klikt op maak film aan.',
        'Systeem valideert ingevulde gegevens.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Er is een nieuwe film aangemaakt.',
    },
    {
      id: 'UC-201',
      name: 'Bijwerken film',
      description: 'Hiermee werkt een administrator een bestaande film bij.',
      scenario: [
        'Actor klikt op de films knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle films.',
        'Actor klikt op het edit icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden met de gegevens van de film.',
        'Actor past de velden naar keuze aan.',
        'Actor klikt op werk film bij.',
        'Systeem valideert ingevulde gegevens.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen film is bijgewerkt.',
    },
    {
      id: 'UC-202',
      name: 'Verwijderen film',
      description: 'Hiermee verwijdert een administrator een bestaande film.',
      scenario: [
        'Actor klikt op de films knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle films.',
        'Actor klikt op het delete icoontje bij een film naar keuze.',
        'Er verschijnt een modal of message die vraagt of de actor de gekozen film wilt verwijderen',
        'Actor klikt op verwijder.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen film is verwijderd.',
    },
    {
      id: 'UC-203',
      name: 'Alle films ophalen',
      description: 'Hiermee haalt een actor alle films op.',
      scenario: ['Actor klikt op de films knop in de navbar.'],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'Geen',
      postcondition:
        'Er verschijnt een pagina met een overzicht van alle films.',
    },
    {
      id: 'UC-204',
      name: 'Details en voorstellingen van een film ophalen',
      description:
        'Hiermee haalt een actor de details en de voorstellingen van een film op.',
      scenario: [
        'Actor klikt op de films knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle films.',
        'Actor klikt op een film naar keuze.',
      ],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'Geen',
      postcondition:
        'De detail pagina met de voorstellingen van een film verschijnt.',
    },
    {
      id: 'UC-205',
      name: 'Film toevoegen aan lijst',
      description:
        'Hiermee voegt een actor een film toe aan zijn of haar lijst.',
      scenario: [
        'Actor klikt op films.',
        'Er verschijnt een pagina met een overzicht van alle films.',
        'Actor klikt op een film naar keuze.',
        'Er verschijnt een detail pagina van de gekozen film.',
        'Scroll naar benden en klik op de add film to my list knop',
      ],
      actor: `${this.PLAIN_USER}`,
      precondition: 'Gebruiker is ingelogd',
      postcondition:
        'De gekozen film is toegevoegd aan de ljst van de ingelogde gebruiker.',
    },
    {
      id: 'UC-206',
      name: 'Film verwijderen uit lijst',
      description:
        'Hiermee verwijdert een actor een film uit zijn of haar lijst.',
      scenario: [
        'Actor klikt op zijn email adres in de navbar.',
        'Actor klikt op my profile uit de dropdown',
        'Er verschijnt een pagina met daarop de gegevens van de ingelogde gebruiker.',
        'Actor scrollt naar zijn film list.',
        'Actor klikt op het verwijder icoontje bij de film naar keuze.',
      ],
      actor: `${this.PLAIN_USER}`,
      precondition: 'Gebruiker is ingelogd',
      postcondition:
        'De gekozen film is verwijderd uit de ljst van de ingelogde gebruiker.',
    },
    {
      id: 'UC-300',
      name: 'Aanmaken zaal',
      description: 'Hiermee maakt een administrator een nieuwe zaal aan.',
      scenario: [
        'Actor klikt op de zalen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle zalen.',
        'Actor klikt op het + icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden.',
        'Actor vult de velden in.',
        'Actor klikt op maak zaal aan.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Er is een nieuwe zaal aangemaakt.',
    },
    {
      id: 'UC-301',
      name: 'Bijwerken zaal',
      description: 'Hiermee werkt een administrator een bestaande zaal bij.',
      scenario: [
        'Actor klikt op de zalen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle zalen.',
        'Actor klikt op het edit icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden met de gegevens van de zaal.',
        'Actor past de velden naar keuze aan.',
        'Actor klikt op werk zaal bij.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen zaal is bijgewerkt.',
    },
    {
      id: 'UC-302',
      name: 'Verwijderen zaal',
      description: 'Hiermee verwijdert een administrator een bestaande zaal.',
      scenario: [
        'Actor klikt op de zalen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle zalen.',
        'Actor klikt op het verwijder icoontje bij een zaal naar keuze.',
        'Er verschijnt een modal of message die vraagt of de actor de gekozen zaal wilt verwijderen',
        'Actor klikt op verwijder.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Een gekozen zaal is verwijderd.',
    },
    {
      id: 'UC-303',
      name: 'Alle zalen ophalen',
      description: 'Hiermee haalt een actor alle zalen op.',
      scenario: ['Actor klikt op de halls knop in de navbar.'],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition:
        'Er verschijnt een pagina met een overzicht van alle zalen.',
    },
    {
      id: 'UC-304',
      name: 'Details van een zaal ophalen',
      description: 'Hiermee haalt een actor de details van een zaal op.',
      scenario: [
        'Actor klikt op de halls knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle zalen.',
        'Actor klikt op een zaal naar keuze.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition: 'De detail pagina van een zaal verschijnt.',
    },
    {
      id: 'UC-400',
      name: 'Aanmaken voorstelling',
      description:
        'Hiermee maakt een administrator een nieuwe voorstelling aan.',
      scenario: [
        'Actor klikt op de voorstellingen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle voorstellingen.',
        'Actor klikt op het + icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden.',
        'Actor vult de velden in.',
        'Actor klikt op maak voorstelling aan.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Er is een nieuwe voorstelling aangemaakt.',
    },
    {
      id: 'UC-401',
      name: 'Bijwerken voortstelling',
      description:
        'Hiermee werkt een administrator een bestaande voorstelling bij.',
      scenario: [
        'Actor klikt op de voorstellingen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle voorstellingen.',
        'Actor klikt op het edit icoontje.',
        'Er verschijnt een pagina met verschillende invoervelden met de gegevens van de voorstelling.',
        'Actor past de velden naar keuze aan.',
        'Actor klikt op werk voorstelling bij.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen voorstelling is bijgewerkt.',
    },
    {
      id: 'UC-402',
      name: 'Verwijderen voorstelling',
      description:
        'Hiermee verwijdert een administrator een bestaande voorstelling.',
      scenario: [
        'Actor klikt op de voorstellingen knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle voorstellingen.',
        'Actor klikt op het verwijder icoontje bij een voorstelling naar keuze.',
        'Er verschijnt een modal of message die vraagt of de actor de gekozen voorstelling wilt verwijderen',
        'Actor klikt op verwijder.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Een gekozen voorstelling is verwijderd.',
    },
    {
      id: 'UC-403',
      name: 'Alle voorstellingen ophalen',
      description: 'Hiermee haalt een actor alle voorstellingen op.',
      scenario: ['Actor klikt op de screenings knop in de navbar.'],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'Geen',
      postcondition:
        'Er verschijnt een pagina met een overzicht van alle voorstellingen.',
    },
    {
      id: 'UC-404',
      name: 'Details van een voorstelling ophalen',
      description:
        'Hiermee haalt een actor de details van een voorstelling op.',
      scenario: [
        'Actor klikt op de screenings knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle voorstellingen.',
        'Actor klikt op een voorstelling naar keuze.',
      ],
      actor: `${this.PLAIN_USER} & ${this.ADMIN_USER}`,
      precondition: 'Geen',
      postcondition: 'De detail pagina van een voorstelling verschijnt.',
    },
    {
      id: 'UC-501',
      name: 'Bijwerken gebruiker',
      description:
        'Hiermee werkt een administrator een bestaande gebruiker bij.',
      scenario: [
        'Actor klikt op de users knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle gebruikers.',
        'Actor klikt op het edit icoontje van een gebruiker naar keuze.',
        'Er verschijnt een pagina met verschillende invoervelden met de gegevens van de gebruiker.',
        'Actor past de velden naar keuze aan.',
        'Actor klikt op werk gebruiker bij knop.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen gebruiker is bijgewerkt.',
    },
    {
      id: 'UC-502',
      name: 'Verwijderen gebruiker',
      description:
        'Hiermee verwijdert een administrator een bestaande gebruiker.',
      scenario: [
        'Actor klikt op de users knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle gebruiker.',
        'Actor klikt op het verwijder icoontje bij een gebruiker naar keuze.',
        'Er verschijnt een modal of message die vraagt of de actor de gekozen gebruiker wilt verwijderen',
        'Actor klikt op verwijder.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Een gekozen gebruiker is verwijderd.',
    },
    {
      id: 'UC-503',
      name: 'Alle gebruikers ophalen',
      description: 'Hiermee haalt een actor alle gebruikers op.',
      scenario: ['Actor klikt op de users knop in de navbar.'],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition:
        'Er verschijnt een pagina met een overzicht van alle gebruiker.',
    },
    {
      id: 'UC-504',
      name: 'Details van een gebruiker ophalen',
      description: 'Hiermee haalt een actor de details van een gebruiker op.',
      scenario: [
        'Actor klikt op de users knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle gebruikers.',
        'Actor klikt op het detail icoontje van een gebruiker naar keuze.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition: 'De detail pagina van een gebruiker verschijnt.',
    },
    {
      id: 'UC-505',
      name: 'Gebruiker volgen',
      description: 'Hiermee volgt een gebruiker een andere gebruiker.',
      scenario: [
        'Actor klikt op people.',
        'Er verschijnt een pagina met een overzicht van alle gebruikers.',
        'Actor klikt op het plus icoontje van een gebruiker naar keuze.',
      ],
      actor: `${this.PLAIN_USER}`,
      precondition: 'Gebruiker is ingelogd',
      postcondition: 'De gekozen gebruiker wordt gevolgd.',
    },
    {
      id: 'UC-506',
      name: 'Volgende gebruiker ontvolgen.',
      description: 'Hiermee ontvolgt een actor een andere gebruiker.',
      scenario: [
        'Actor klikt op zijn email adres in de navbar.',
        'Actor klikt op my profile uit de dropdown',
        'Er verschijnt een pagina met daarop de gegevens van de ingelogde gebruiker.',
        'Actor scrollt naar zijn following list.',
        'Actor klikt op het verwijder icoontje bij de gebruiker naar keuze.',
      ],
      actor: `${this.PLAIN_USER}`,
      precondition: 'Gebruiker is ingelogd',
      postcondition: 'De gekozen gebruiker is ontvolgt..',
    },
    {
      id: 'UC-601',
      name: 'Bijwerken acteur',
      description: 'Hiermee werkt een administrator een bestaande acteur bij.',
      scenario: [
        'Actor klikt op de actors knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle acteurs.',
        'Actor klikt op het edit icoontje van een acteur naar keuze.',
        'Er verschijnt een pagina met verschillende invoervelden met de gegevens van de acteur.',
        'Actor past de velden naar keuze aan.',
        'Actor klikt op werk acteur bij knop.',
        'Systeem valideert ingevulde gegevens',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'De gekozen acteur is bijgewerkt.',
    },
    {
      id: 'UC-602',
      name: 'Verwijderen acteur',
      description:
        'Hiermee verwijdert een administrator een bestaande gebruiker.',
      scenario: [
        'Actor klikt op de actors knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle acteurs.',
        'Actor klikt op het verwijder icoontje bij een acteur naar keuze.',
        'Er verschijnt een modal of message die vraagt of de actor de gekozen acteur wilt verwijderen',
        'Actor klikt op verwijder.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'De administrator is ingelogd.',
      postcondition: 'Een gekozen acteur is verwijderd.',
    },
    {
      id: 'UC-603',
      name: 'Alle acteurs ophalen',
      description: 'Hiermee haalt een actor alle acteurs op.',
      scenario: ['Actor klikt op de actors knop in de navbar.'],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition:
        'Er verschijnt een pagina met een overzicht van alle acteurs.',
    },
    {
      id: 'UC-604',
      name: 'Details van een acteur ophalen',
      description: 'Hiermee haalt een actor de details van een acteur op.',
      scenario: [
        'Actor klikt op de actors knop in de navbar.',
        'Er verschijnt een pagina met een overzicht van alle gebruikers.',
        'Actor klikt op het detail icoontje van een acteur naar keuze.',
      ],
      actor: this.ADMIN_USER,
      precondition: 'Geen',
      postcondition: 'De detail pagina van een acteur verschijnt.',
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}
